
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay
 */
public class AddQuestion extends javax.swing.JFrame {

    int id,total_q=0;
    /**
     * Creates new form AddQuestion
     */
    public AddQuestion() {
        initComponents();
        id=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        colon = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        skip = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        answer = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Question_Field = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Field_D = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        RadioD = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Field_C = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        RadioC = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        RadioA = new javax.swing.JRadioButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        Field_A = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Field_B = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        RadioB = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        Q_ID_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Question_number = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("SKIP THIS QUESTION");
        jButton3.setEnabled(false);
        jButton3.setOpaque(false);
        jPanel7.add(jButton3);
        jButton3.setBounds(20, 360, 160, 50);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        min.setForeground(new java.awt.Color(0, 51, 153));
        min.setText("29");
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        colon.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        colon.setText(":");
        jPanel1.add(colon, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, -1, -1));

        sec.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        sec.setForeground(new java.awt.Color(0, 51, 153));
        sec.setText("59");
        jPanel1.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 11, -1, -1));

        jPanel7.add(jPanel1);
        jPanel1.setBounds(10, 10, 180, 90);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        skip.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        skip.setForeground(new java.awt.Color(0, 0, 204));
        skip.setText("5");
        skip.setEnabled(false);
        jPanel6.add(skip);
        skip.setBounds(60, 60, 31, 58);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("SKIP LEFT");
        jLabel6.setEnabled(false);
        jPanel6.add(jLabel6);
        jLabel6.setBounds(10, 0, 140, 50);

        jPanel7.add(jPanel6);
        jPanel6.setBounds(20, 230, 160, 130);

        jButton1.setText("Add Question to database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jButton1.setBounds(20, 450, 160, 23);
        jPanel7.add(answer);
        answer.setBounds(20, 560, 150, 40);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        Question_Field.setColumns(20);
        Question_Field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Question_Field.setLineWrap(true);
        Question_Field.setRows(5);
        Question_Field.setWrapStyleWord(true);
        Question_Field.setOpaque(false);
        jScrollPane1.setViewportView(Question_Field);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1097, 165));

        jPanel2.setOpaque(false);

        jScrollPane10.setOpaque(false);

        Field_D.setColumns(20);
        Field_D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_D.setLineWrap(true);
        Field_D.setRows(5);
        Field_D.setWrapStyleWord(true);
        Field_D.setOpaque(false);
        jScrollPane10.setViewportView(Field_D);

        jScrollPane6.setOpaque(false);

        RadioD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioD.setForeground(new java.awt.Color(0, 0, 153));
        RadioD.setText("D");
        RadioD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioD.setEnabled(false);
        RadioD.setOpaque(false);
        RadioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDActionPerformed(evt);
            }
        });
        jScrollPane6.setViewportView(RadioD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1097, -1));

        jPanel4.setOpaque(false);

        jScrollPane9.setOpaque(false);

        Field_C.setColumns(20);
        Field_C.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_C.setLineWrap(true);
        Field_C.setRows(5);
        Field_C.setWrapStyleWord(true);
        Field_C.setOpaque(false);
        jScrollPane9.setViewportView(Field_C);

        jScrollPane5.setOpaque(false);

        RadioC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioC.setForeground(new java.awt.Color(0, 0, 153));
        RadioC.setText("C");
        RadioC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioC.setEnabled(false);
        RadioC.setOpaque(false);
        RadioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCActionPerformed(evt);
            }
        });
        jScrollPane5.setViewportView(RadioC);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, -1, -1));

        jPanel8.setOpaque(false);

        jScrollPane3.setOpaque(false);

        RadioA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioA.setForeground(new java.awt.Color(0, 0, 153));
        RadioA.setText("A");
        RadioA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioA.setEnabled(false);
        RadioA.setOpaque(false);
        RadioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAActionPerformed(evt);
            }
        });
        jScrollPane3.setViewportView(RadioA);

        jScrollPane7.setOpaque(false);

        Field_A.setColumns(20);
        Field_A.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_A.setLineWrap(true);
        Field_A.setRows(5);
        Field_A.setWrapStyleWord(true);
        Field_A.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Field_A.setOpaque(false);
        jScrollPane7.setViewportView(Field_A);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane7))
                .addGap(1, 1, 1))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 1097, -1));

        jPanel5.setOpaque(false);

        jScrollPane8.setOpaque(false);

        Field_B.setColumns(20);
        Field_B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_B.setLineWrap(true);
        Field_B.setRows(5);
        Field_B.setWrapStyleWord(true);
        Field_B.setOpaque(false);
        jScrollPane8.setViewportView(Field_B);

        jScrollPane4.setOpaque(false);

        RadioB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioB.setForeground(new java.awt.Color(0, 0, 153));
        RadioB.setText("B");
        RadioB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioB.setEnabled(false);
        RadioB.setOpaque(false);
        RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBActionPerformed(evt);
            }
        });
        jScrollPane4.setViewportView(RadioB);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 279, -1, -1));

        jPanel10.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Question :");

        Question_number.setText("1");

        jLabel2.setText("ID :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question_number, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Question_number)
                        .addComponent(jLabel2))
                    .addComponent(Q_ID_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Answer");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(33, 33, 33)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(550, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_RadioDActionPerformed

    private void RadioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCActionPerformed
        // TODO add your handling code here:

      

    }//GEN-LAST:event_RadioCActionPerformed

    private void RadioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAActionPerformed

        

        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAActionPerformed

    private void RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_RadioBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(!answer.equals(""))
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(Akz.ip, "root", "");
            //mysql server
            Statement st=con.createStatement();

            //ResultSet rs=st.executeQuery("select * from APP.student");
            ResultSet rs_qna=st.executeQuery("select * from qna");//mysql server
            //ResultSetMetaData meta=rs.getMetaData();
            int total_q=0;
            while(rs_qna.next()){
               total_q++;
            }
            id=total_q+1;
            JOptionPane.showMessageDialog(null,"This will be Q no. "+id+".");
            st.executeUpdate("insert into qna(question,a,b,c,d,id,answer) values('"+Question_Field.getText()+"','"+Field_A.getText()+"','"+Field_B.getText()+"','"+Field_C.getText()+"','"+Field_D.getText()+"','"+(id)+"','"+answer.getText()+"')");
            JOptionPane.showMessageDialog(null,"Question Added Successfully");
            
            id++;
            Question_number.setText(""+id);
            Question_Field.setText("");
            Field_A.setText("");
            Field_B.setText("");
            Field_C.setText("");
            Field_D.setText("");
            answer.setText("");
            
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }
    else{
        JOptionPane.showMessageDialog(null, "Answer????");
    }


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        this.setVisible(false);
        AdminPage adp=new AdminPage();
        adp.setVisible(true);



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Field_A;
    public static javax.swing.JTextArea Field_B;
    public static javax.swing.JTextArea Field_C;
    public static javax.swing.JTextArea Field_D;
    public static javax.swing.JLabel Q_ID_label;
    public static javax.swing.JTextArea Question_Field;
    private javax.swing.JLabel Question_number;
    private javax.swing.JRadioButton RadioA;
    private javax.swing.JRadioButton RadioB;
    private javax.swing.JRadioButton RadioC;
    private javax.swing.JRadioButton RadioD;
    private javax.swing.JTextField answer;
    public static javax.swing.JLabel colon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JLabel min;
    public static javax.swing.JLabel sec;
    private javax.swing.JLabel skip;
    // End of variables declaration//GEN-END:variables
}
