
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay
 */

public class StudentPage extends javax.swing.JFrame {
  
   //// static String usr_global,name_global;
   // int score_global;
    int answersaved=2,count_colon,index=1;
    static int skips=3,consecutive=0;
    static public ResultSet current_user_set;
    static int score=0;
    static int scoreplus=4,scoreneg=0;
   
    /**
     * Creates new form StudentPage
     */
    static boolean submitted=false;
   
      
    
    
    public StudentPage() {
        this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
         /*if(AdminPage.skip_disable){
             StudentPage.skip.setText(""+0);
             StudentPage.jButton3.setEnabled(false);
         }*/
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=tk.getScreenSize().width;
        int ysize=tk.getScreenSize().height;
        this.setSize(xsize, ysize);
        skips=3;
        
        
       /* final Timer timer_colon = new Timer();
        
        count_colon = 2; 
        TimerTask task = new TimerTask() {         
            public void run() {  
                count_colon--;
                
                if(count_colon==0)
                {
                    colon.setText("");
                    count_colon=2;
                }
                else
                colon.setText(":");
            }         
            
        };
        timer_colon.scheduleAtFixedRate(task, 0,1000); */
       
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Question_Field = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        Field_D = new javax.swing.JTextArea();
        RadioD = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        Field_C = new javax.swing.JTextArea();
        RadioC = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        Field_A = new javax.swing.JTextArea();
        RadioA = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        Field_B = new javax.swing.JTextArea();
        RadioB = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        colon = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        skip = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        welcomestudentpage = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Q_ID_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Question_number = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        Question_Field.setEditable(false);
        Question_Field.setColumns(20);
        Question_Field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Question_Field.setLineWrap(true);
        Question_Field.setRows(5);
        Question_Field.setText("Loading...");
        Question_Field.setWrapStyleWord(true);
        Question_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Question_Field.setOpaque(false);
        jScrollPane1.setViewportView(Question_Field);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 1020, 165));

        jPanel2.setOpaque(false);

        Field_D.setEditable(false);
        Field_D.setColumns(20);
        Field_D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_D.setLineWrap(true);
        Field_D.setRows(5);
        Field_D.setWrapStyleWord(true);
        Field_D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Field_D.setOpaque(false);

        buttonGroup1.add(RadioD);
        RadioD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioD.setForeground(new java.awt.Color(0, 0, 153));
        RadioD.setText("D");
        RadioD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioD.setOpaque(false);
        RadioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(RadioD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_D, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioD, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Field_D, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1080, 100));

        jPanel4.setOpaque(false);

        Field_C.setEditable(false);
        Field_C.setColumns(20);
        Field_C.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_C.setLineWrap(true);
        Field_C.setRows(5);
        Field_C.setWrapStyleWord(true);
        Field_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Field_C.setOpaque(false);

        buttonGroup1.add(RadioC);
        RadioC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioC.setForeground(new java.awt.Color(0, 0, 153));
        RadioC.setText("C");
        RadioC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioC.setOpaque(false);
        RadioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(RadioC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_C, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioC, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Field_C, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, -1, 100));

        jPanel8.setOpaque(false);

        Field_A.setEditable(false);
        Field_A.setColumns(20);
        Field_A.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_A.setLineWrap(true);
        Field_A.setRows(5);
        Field_A.setWrapStyleWord(true);
        Field_A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Field_A.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Field_A.setOpaque(false);

        buttonGroup1.add(RadioA);
        RadioA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioA.setForeground(new java.awt.Color(0, 0, 153));
        RadioA.setText("A");
        RadioA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioA.setOpaque(false);
        RadioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(RadioA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Field_A, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioA, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field_A, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 1080, 90));

        jPanel5.setOpaque(false);

        Field_B.setEditable(false);
        Field_B.setColumns(20);
        Field_B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Field_B.setLineWrap(true);
        Field_B.setRows(5);
        Field_B.setWrapStyleWord(true);
        Field_B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Field_B.setOpaque(false);

        buttonGroup1.add(RadioB);
        RadioB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RadioB.setForeground(new java.awt.Color(0, 0, 153));
        RadioB.setText("B");
        RadioB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioB.setOpaque(false);
        RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_B, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Field_B, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioB, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 90));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 120, 1110, 590);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("SKIP THIS QUESTION");
        jButton3.setEnabled(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(20, 360, 160, 50);

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(204, 0, 0));
        submit.setText("SUBMIT EXAM");
        submit.setOpaque(false);
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel7.add(submit);
        submit.setBounds(20, 123, 160, 40);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        min.setForeground(new java.awt.Color(0, 51, 153));
        min.setText("29");
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        colon.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        colon.setText(":");
        jPanel1.add(colon, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, -1, -1));

        sec.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        sec.setForeground(new java.awt.Color(0, 51, 153));
        sec.setText("59");
        jPanel1.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 11, -1, -1));

        jPanel7.add(jPanel1);
        jPanel1.setBounds(10, 10, 180, 90);

        next.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        next.setText("NEXT");
        next.setOpaque(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel7.add(next);
        next.setBounds(20, 510, 160, 90);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        skip.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        skip.setForeground(new java.awt.Color(0, 0, 204));
        skip.setText("-");
        jPanel6.add(skip);
        skip.setBounds(40, 60, 60, 58);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("SKIP LEFT");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(10, 0, 120, 50);

        jPanel7.add(jPanel6);
        jPanel6.setBounds(30, 190, 140, 130);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(1120, 10, 200, 620);

        jPanel9.setOpaque(false);

        welcomestudentpage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomestudentpage.setForeground(new java.awt.Color(0, 0, 204));
        welcomestudentpage.setText("Loading...");

        test.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        test.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomestudentpage, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomestudentpage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(130, 10, 970, 67);

        jPanel10.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Question :");

        Question_number.setText("1");

        jLabel2.setText("ID :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question_number, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Question_number)
                        .addComponent(jLabel2))
                    .addComponent(Q_ID_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel10);
        jPanel10.setBounds(130, 80, 210, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/1366 768 world.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
        
        final Timer timer = new Timer();
        
        answersaved = 3; //setting the counter to 10 sec
     
        TimerTask task = new TimerTask() {         
            public void run() {               
                test.setText("Option 'C' Saved.");
                answersaved --;
                if(answersaved==1){
                    answersaved=2;
                    test.setText("");
                    timer.cancel();
                }
            }
            
            
        };
        timer.scheduleAtFixedRate(task, 0,500); 
        
    }//GEN-LAST:event_RadioCActionPerformed

    private void RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBActionPerformed
        // TODO add your handling code here:
        
        final Timer timer = new Timer();
        
        answersaved = 3; //setting the counter to 10 sec
     
        TimerTask task = new TimerTask() {         
            public void run() {               
                test.setText("Option 'B' Saved.");
                answersaved --;
                if(answersaved==1){
                    answersaved=2;
                    test.setText("");
                    timer.cancel();
                }
            }
            
            
        };
        timer.scheduleAtFixedRate(task, 0,500); 
        
        
    }//GEN-LAST:event_RadioBActionPerformed

    private void RadioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDActionPerformed
        // TODO add your handling code here:
        final Timer timer = new Timer();
        
        answersaved = 3; //setting the counter to 10 sec
     
        TimerTask task = new TimerTask() {         
            public void run() {               
                test.setText("Option 'D' Saved.");
                answersaved --;
                if(answersaved==1){
                    answersaved=2;
                    test.setText("");
                    timer.cancel();
                }
            }
            
            
        };
        timer.scheduleAtFixedRate(task, 0,500); 
        
    }//GEN-LAST:event_RadioDActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
      
       
        
    }//GEN-LAST:event_submitActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        
        
        
    if(!RadioA.isSelected() && !RadioB.isSelected() && !RadioC.isSelected() && !RadioD.isSelected())
        test.setText("You have to select an option.");
    else if(index<StudentLogin.total_q){
        
            Question_number.setText(""+(++index));
        try {
          
            //Class.forName("org.apache.derby.jdbc.ClientDriver");
            //Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sun-appserv-samples","APP","APP");
            switch(StudentLogin.Answer_1.toUpperCase()){
                     case "A":
                                if(RadioA.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                                    
                         break;
                     case "B":
                                if(RadioB.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                         break;
                     case "C":
                                if(RadioC.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                         break;
                     case "D":
                                if(RadioD.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                         break;
                         
                 }
        if(consecutive==3){
          //  skip.setText(""+(++skips));
            consecutive=0;
        }
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://10.11.13.13/viitquiz?zeroDateTimeBehavior=convertToNull","akz","55920982921");
           
            //mysql server
            Statement st=con.createStatement();

           
            
            ResultSet rs_qna1=st.executeQuery("select * from viitquiz.qna where id = "+StudentLogin.ID.get(index-1)+"");
                 rs_qna1.next();
                //System.outp.print(rs_qna.getObject("question"));
                // System.out.print("\nyha tak to chl gya2"+rs_qna1.getObject("question").toString());
                 StudentPage.Question_Field.setText(rs_qna1.getObject("question").toString());
                 Question_Field.setCaretPosition(0);
                 
                 StudentPage.Field_A.setText(rs_qna1.getObject("a").toString());
                 StudentPage.Field_B.setText(rs_qna1.getObject("b").toString());
                 StudentPage.Field_C.setText(rs_qna1.getObject("c").toString());
                 StudentPage.Field_D.setText(rs_qna1.getObject("d").toString());
                 Q_ID_label.setText(rs_qna1.getObject("id").toString());
                 String Answer=rs_qna1.getObject("answer").toString();
                 
                 
                 
                 StudentLogin.Answer_1=Answer;
                 
                 buttonGroup1.clearSelection();
                 
            
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    


        
        
    }
    else{
       JOptionPane.showMessageDialog(null,"Maximum Question Limit Reached..!!");
    }


// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void RadioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAActionPerformed

        final Timer timer = new Timer();

        answersaved = 3;
        TimerTask task = new TimerTask() {
            public void run() {
                test.setText("Option 'A' Saved.");
                answersaved --;
                if(answersaved==1){
                    answersaved=2;
                    test.setText("");
                    timer.cancel();
                }
            }

        };
        timer.scheduleAtFixedRate(task, 0,500);

        // TODO add your handling code here:
    }//GEN-LAST:event_RadioAActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

      /*  
        //
        if(skips>0){
            skip.setText(""+(--skips));
            
            
            if(index<StudentLogin.total_q){
        
            Question_number.setText(""+(++index));
        try {
          
            //Class.forName("org.apache.derby.jdbc.ClientDriver");
            //Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sun-appserv-samples","APP","APP");
           /* switch(StudentLogin.Answer_1.toUpperCase()){
                     case "A":
                                if(RadioA.isSelected()){
                                    score+=4;
                                }
                                else
                                    score-=2;
                         break;
                     case "B":
                                if(RadioB.isSelected()){
                                    score+=4;
                                }
                                else
                                    score-=2;
                         break;
                     case "C":
                                if(RadioC.isSelected()){
                                    score+=4;
                                }
                                else
                                    score-=2;
                         break;
                     case "D":
                                if(RadioD.isSelected()){
                                    score+=4;
                                }
                                else
                                    score-=2;
                         break;
                         
                 }*/
 /*           
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://10.11.13.13:3306/viitquiz?zeroDateTimeBehavior=convertToNull","akz","55920982921");
            //mysql server
            Statement st=con.createStatement();

           
            
            ResultSet rs_qna1=st.executeQuery("select * from viitquiz.qna where id = "+StudentLogin.ID.get(index-1)+"");
                 rs_qna1.next();
                //System.out.print(rs_qna.getObject("question"));
                // System.out.print("\nyha tak to chl gya2"+rs_qna1.getObject("question").toString());
                 StudentPage.Question_Field.setText(rs_qna1.getObject("question").toString());
                 Question_Field.setCaretPosition(0);
                 
                 StudentPage.Field_A.setText(rs_qna1.getObject("a").toString());
                 StudentPage.Field_B.setText(rs_qna1.getObject("b").toString());
                 StudentPage.Field_C.setText(rs_qna1.getObject("c").toString());
                 StudentPage.Field_D.setText(rs_qna1.getObject("d").toString());
                 Q_ID_label.setText(rs_qna1.getObject("id").toString());
                 String Answer=rs_qna1.getObject("answer").toString();
                 
                 
                 
                 StudentLogin.Answer_1=Answer;
                 
                 buttonGroup1.clearSelection();
                 
            
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    


        
        
    }
    else{
       JOptionPane.showMessageDialog(null,"Maximum Question Limit Reached..!!");
    }
        }
        else{
           
            
        final Timer timer = new Timer();

        answersaved = 3;
        TimerTask task = new TimerTask() {
            public void run() {
                test.setText("No Skip Left.!");
                answersaved --;
                if(answersaved==1){
                    answersaved=2;
                    test.setText("");
                    timer.cancel();
                }
            }

        };
        timer.scheduleAtFixedRate(task, 0,500);

        }*/
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            
        switch(StudentLogin.Answer_1.toUpperCase()){
                     case "A":
                                if(RadioA.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                                    
                         break;
                     case "B":
                                if(RadioB.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                         break;
                     case "C":
                                if(RadioC.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                         break;
                     case "D":
                                if(RadioD.isSelected()){
                                    score+=scoreplus;
                                    consecutive++;
                                }
                                else{
                                    score-=scoreneg;
                                    consecutive=0;                                    
                                }
                         break;
                     default:
                         break;
                         
                 }
        if(consecutive==3){
          //  skip.setText(""+(++skips));
            consecutive=0;
        }
        
        
        
      try{

            //Class.forName("org.apache.derby.jdbc.ClientDriver");
            //Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sun-appserv-samples","APP","APP");
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://10.11.13.13/viitquiz?zeroDateTimeBehavior=convertToNull","akz","55920982921");
            //mysql server
            Statement st=con.createStatement();

          
            
            
            thanks ty=new thanks();       
            this.setVisible(false);
            ty.setVisible(true);
            
            thanks.thanks_name.setText(StudentLogin.name);
            thanks.thanks_score.setText(""+score);
            st.executeUpdate("update student set given = 1, score="+score+" where username = '"+StudentLogin.user_global+"'");
            score=0;
            StudentPage.score=0;
            
           //new current_user_set after updation
            //ResultSet rs=st.executeQuery("select * from APP.student");
           /* ResultSet rs=st.executeQuery("select * from quiz.student");//mysql server
            while(rs.next()){
                if(rs.getObject("username").equals(current_user_set.getObject("username"))){
                    current_user_set=rs;
                }
                
                //updation of current user set completed
                
            }*/
            submitted=true;
          }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
     
    public void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
      

       
    
        
        
        
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Field_A;
    public static javax.swing.JTextArea Field_B;
    public static javax.swing.JTextArea Field_C;
    public static javax.swing.JTextArea Field_D;
    public static javax.swing.JLabel Q_ID_label;
    public static javax.swing.JTextArea Question_Field;
    private javax.swing.JLabel Question_number;
    public static javax.swing.JRadioButton RadioA;
    public static javax.swing.JRadioButton RadioB;
    public static javax.swing.JRadioButton RadioC;
    public static javax.swing.JRadioButton RadioD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    public static javax.swing.JLabel colon;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel min;
    private javax.swing.JButton next;
    public static javax.swing.JLabel sec;
    private javax.swing.JLabel skip;
    private javax.swing.JButton submit;
    private javax.swing.JLabel test;
    public static javax.swing.JLabel welcomestudentpage;
    // End of variables declaration//GEN-END:variables
 
    

      
}


